apiVersion: v1
kind: Secret
metadata:
  name: hangar-zipkin
  labels:
    {{- include "hangar.labels" . | nindent 4 }}
type: Opaque
stringData:
  TEST: "{{ .Values.zipkin.config.test }}"
  STORAGE_TYPE: mem
