{{- if .Values.zipkin.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hangar.zipkin.serviceAccountName" . }}
  labels:
    {{- include "hangar.labels" . | nindent 4 }}
  {{- with .Values.zipkin.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
