apiVersion: v1
kind: Service
metadata:
  name: {{ include "hangar.fullname" . }}-zipkin
  labels:
    {{- include "hangar.labels" . | nindent 4 }}
  annotations:
    service.kubernetes.io/topology-aware-hints: "auto"
spec:
  type: {{ .Values.zipkin.service.type }}
  ports:
    - port: {{ .Values.zipkin.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hangar.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "zipkin"
